# --- !Ups
CREATE TABLE USER
(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(40) NOT NULL,
  PASSWORD VARCHAR(40) NOT NULL,
  PRIMARY KEY(ID)
);


INSERT INTO USER VALUES (1,'CZW','a');
INSERT INTO USER VALUES (2,'DADANIU','a');

# --- !Downs

DROP TABLE USER;