# --- !Ups
CREATE TABLE USER
(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(40) NOT NULL,
  PASSWORD VARCHAR(40) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE STOCK
(
  CODE VARCHAR(10),
  SHORT_NAME VARCHAR(40),
  FULL_NAME VARCHAR(80),
  INDUSTRY VARCHAR(80),
  WEBSITE VARCHAR(256),
  PRIMARY KEY (CODE)
);


INSERT INTO USER VALUES (1,'CZW','a');
INSERT INTO USER VALUES (2,'DADANIU','a');

# --- !Downs

DROP TABLE USER;