# --- !Ups
CREATE TABLE USER
(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(40) NOT NULL,
  PASSWORD VARCHAR(40) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE STOCK
(
  CODE VARCHAR(10),
  SHORT_NAME VARCHAR(40),
  FULL_NAME VARCHAR(80),
  INDUSTRY VARCHAR(80),
  WEBSITE VARCHAR(256),
  PRIMARY KEY (CODE)
);

CREATE TABLE PLATE
(
  ID INT NOT NULL AUTO_INCREMENT,
  CODE VARCHAR(10),
  SHORT_NAME VARCHAR(40),
  DESCRIPTION VARCHAR(80),
  PRIMARY KEY (ID)
);

# --- !Downs

DROP TABLE USER;
DROP TABLE STOCK;
DROP TABLE PLATE;
